### ISSUE TITLE
wifi hotspot and client

### ISSUE THREAD

**Issue by matt2005** [matt2005/csng_yocto#9]
@adrianalin I've created this for your work

**Comment by adrianalin** [comment]
Ok, i was wondering how to treat the changes needed for git://github.com/opencardev/crankshaft.git ? Should i just add patches as i did until now (like https://github.com/matt2005/csng_yocto/blob/main/meta-crankshaft/recipes-crankshaft/crankshaft/crankshaft/0001-Update-to-new-paths-for-yocto-build.patch)? 

Or should we have a separate branch of crankshaft (where we adjust things) to be used for yocto build?
